### ISSUE TITLE
Supplier Expenditure Report: Selecting Supplier Expenditure Report results in 404 error

### ISSUE THREAD

**Issue by markdatalou** [ram182/ram-pps#11]
Recreate Steps
Goto: http://accessmediallc.com/pps2-test/internaluser
Click on REPORTING
Click on Supplier Expenditure Report
Leads to this result
![image](https://user-images.githubusercontent.com/19581030/33274632-96c93e00-d35e-11e7-9be0-926fc3172764.png)

**Comment by markdatalou** [comment]
I tried it again. Now I just get a blank page
![image](https://user-images.githubusercontent.com/19581030/33275906-f656bcd2-d361-11e7-817e-41bfc7b7ede1.png)

**Comment by ram182** [comment]
yes, because is a test, now I can add my codes

**Comment by markdatalou** [comment]
ok. Understood

**Comment by markdatalou** [comment]
Robert, remember, the person that opens the issue (me) is the person who closes the issue.

**Comment by ram182** [comment]
ok I got it
