### ISSUE TITLE
Running Supplier Expenditure Report - Drill down does not show tax ID

### ISSUE THREAD

**Issue by markdatalou** [ram182/ram-pps#4]
SUMMARY: Started the Supplier Expenditure Report and selected Network=SSNA and Agency=ss_agency_01 and clicked on GET REPORT. When the report rendered, selected row with supplier = test-min and clicked on transactions. 
The transactions screen rendered, but the tax ID field was blank.

**Comment by ram182** [comment]
it's fixed, 
the customer query was added, it was not by confusion of term company = customer
thanks
