### ISSUE TITLE
Supplier Expenditure Report: Unable to click on transaction to drill down in Safari browser

### ISSUE THREAD

**Issue by markdatalou** [ram182/ram-pps#5]
SUMMARY: When running Supplier Expenditure Report in the Safari browser, I am able to run the Supplier Expenditure Report and see the results. However, if I attempt to click on the transaction number, the hand does not show.

**Comment by ram182** [comment]
fixed, styles issues with chrome and safari explorers

**Comment by markdatalou** [comment]
I have verified. Looks good! Closing.
