### ISSUE TITLE
Supplier Expenditure Report: selected Network=testenv and Supplier=fancy pants online inc. - I expected to see list of fancy pants only

### ISSUE THREAD

**Issue by markdatalou** [ram182/ram-pps#7]
As you can see in the image below, I selected NETWORK=testenv and SUPPLIER=Fancy Pants Online Inc. and clicked GET REPORT. The report shows fancy pants and other vendors as well. 

I expected to see a report that only contained Fancy Pants Online  only. 

![image](https://user-images.githubusercontent.com/19581030/32842997-9a610744-c9ec-11e7-8811-619d09d92a33.png)

**Comment by ram182** [comment]
Fixed, thanks
