### ISSUE TITLE
Supplier Expenditure Report: Selecting Network and Company only will sometimes result in error logs

### ISSUE THREAD

**Issue by markdatalou** [ram182/ram-pps#8]
See selection and results below. I selected NETWORK=testenv and Company=test company two
and clicked on GET REPORT. 

![image](https://user-images.githubusercontent.com/19581030/32846455-4bb47ac8-c9f5-11e7-89f4-ea66a2d5adf7.png)

**Comment by ram182** [comment]
Fixed, thanks
